### ISSUE TITLE
Plugin doesn't take Vercel Authorization

### ISSUE THREAD

**Issue by NEDDL** [frencojobs/vscode-vercel#17]
I authorize the plugin on Vercel but it doesn't login in Visual Studio Code

**Comment by snikch** [comment]
Same issue here. Looks like it's trying to use a port that's already allocated to another extension.
```
2023-07-21 17:48:04.638 [error] Error: listen EADDRINUSE: address already in use :::31415
	at Server.setupListenHandle [as _listen2] (node:net:1432:16)
	at listenInCluster (node:net:1480:12)
	at Server.listen (node:net:1568:7)
	at d.listen (/home/mal/.vscode-server/extensions/frenco.vscode-vercel-1.0.3/dist/extension.js:1:44411)
	at t.VercelManager.logIn (/home/mal/.vscode-server/extensions/frenco.vscode-vercel-1.0.3/dist/extension.js:1:41493)
```

**Comment by erbanku** [comment]
Same issue here.

**Comment by chris-erickson** [comment]
Same, looks like a great extension though!

**Comment by kyswtn** [comment]
Hello, I've had the project transferred to me at [kyswtn/vscode-vercel](https://github.com/kyswtn/vscode-vercel) and I plan to maintain it. A lot of bugs including this one has been fixed and a lot more features have been added. Take a look if ur still interested in the extension!

**Comment by chris-erickson** [comment]
Can you get the original maintainer to note that here? It's a little odd to just copy/paste the code over rather than having them actually transfer ownership, make you an admin, or for you to fork it.

**Comment by kyswtn** [comment]
It's not copy/paste. It's a whole new thing entirely. When I said transferred, I meant the ownership of the extension ID on VSCode Marketplace so that I can publish to it. That's the only thing that stays. I now have that and published v2 there.

**Comment by chris-erickson** [comment]
Thanks for the clarification!
